version: '2'
services:
  server:
    command: ["npm","start"]
    links:
     - testdb
    ports:
     - "3000:3000"
    environment:
      NODE_ENV: test
  test:
    depends_on:
     - server
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    command: ["ng","test"]
    links:
     - testdb
volumes:
  test_data:

